In [1]:
import torch

In [2]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)

print(x)
print(x.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [3]:
torch.manual_seed(190401009)

w1 = torch.randn(3, 50)
b1 = torch.randn(1, 50)

w2 = torch.randn(50, 1)
b2 = torch.randn(1, 1)

In [4]:
def sigmoid_func(x):
    return 1 / (1 + torch.exp(-x))

def tanh_func(x):
    return (torch.exp(x) - torch.exp(-x)) / (torch.exp(x) + torch.exp(-x))

In [5]:
tmp = torch.matmul(x, w1) + b1
tmp

tensor([[  3.6372,  -3.0786,  -1.6610,   1.8164,   6.7588,   6.4580,  -1.9611,
          -1.5384,  -7.3956,  -2.9245,  -2.5226,  -5.4705,  -3.5027,  -2.4919,
           4.9809,   1.2226,  -1.4371,  -2.6147,   1.8259,  -3.6015,  12.1292,
          -0.1467,  -2.2208,   6.3313,  -7.1737,   4.5046,  -2.2398,  -1.9947,
           2.7038,  -7.5238,  -1.8929,   3.0155,  -3.2543,  -4.4616,  -1.1274,
          -6.0702,   2.1611,   0.0641,   0.6791,   1.8038,  -2.4629,   0.2764,
          -6.3909,   7.1242,   5.8240,  -2.0739,   1.9870,  -0.3511,   3.0336,
          -2.4687],
        [  3.4147,  -9.0819,  -4.1179,   1.6484,  13.9594,  12.4895,  -4.7985,
          -4.0034, -16.3963,  -5.8073,  -4.6715, -12.2339, -11.5416,  -1.3550,
           9.4471,   2.0060,  -4.7007,  -8.1983,   4.8998,  -4.3205,  27.4210,
          -0.0825,  -6.3618,  13.7793, -12.7986,   6.8788, -10.0541,  -6.9943,
           6.2110, -17.6534,  -4.7450,   6.5188,  -0.4872,  -7.7684,  -3.3031,
         -14.5351,   5.5456,  -1

In [6]:
tanh_x = tanh_func(tmp)
tanh_x

tensor([[ 0.9986, -0.9958, -0.9304,  0.9485,  1.0000,  1.0000, -0.9612, -0.9118,
         -1.0000, -0.9943, -0.9872, -1.0000, -0.9982, -0.9864,  0.9999,  0.8404,
         -0.8931, -0.9893,  0.9494, -0.9985,  1.0000, -0.1456, -0.9767,  1.0000,
         -1.0000,  0.9998, -0.9776, -0.9637,  0.9911, -1.0000, -0.9556,  0.9952,
         -0.9970, -0.9997, -0.8101, -1.0000,  0.9738,  0.0640,  0.5909,  0.9472,
         -0.9856,  0.2696, -1.0000,  1.0000,  1.0000, -0.9689,  0.9631, -0.3373,
          0.9954, -0.9858],
        [ 0.9978, -1.0000, -0.9995,  0.9286,  1.0000,  1.0000, -0.9999, -0.9993,
         -1.0000, -1.0000, -0.9998, -1.0000, -1.0000, -0.8752,  1.0000,  0.9645,
         -0.9998, -1.0000,  0.9999, -0.9996,  1.0000, -0.0824, -1.0000,  1.0000,
         -1.0000,  1.0000, -1.0000, -1.0000,  1.0000, -1.0000, -0.9998,  1.0000,
         -0.4520, -1.0000, -0.9973, -1.0000,  1.0000, -0.9050,  0.9085, -0.2803,
         -1.0000,  0.8933, -1.0000,  1.0000,  1.0000, -0.9848,  1.0000, -0.3378,


In [7]:
output = sigmoid_func(torch.matmul(tanh_x, w2) + b2)
output

tensor([[0.0498],
        [0.0075]])